### ISSUE TITLE
Will not pull full file - ERROR

### ISSUE THREAD

**Issue by bludeerro** [breizoreol/memanki-cli#1]
Hey, there's one specific memrise file that won't pull merged and is incomplete when pulled as sub-files. It pulls 22/37 of the files.
**PASTED FROM CMD**
C:\Users\Hero>memanki --id 1123054
Package has been generated: Fuel Your Vocab: Places.apkg
Package has been generated: Getting Fed.apkg
Package has been generated: Retail Therapy.apkg
Package has been generated: Found in Space.apkg
Package has been generated: Fuel Your Vocab: Places to Explore.apkg
Package has been generated: Fuel Your Vocab: Types of Humans.apkg
Package has been generated: In Disguise.apkg
Package has been generated: Fuel Your Vocab: Human Parts.apkg
Package has been generated: Contamination!.apkg
Package has been generated: Impress Them.apkg
Package has been generated: Back at Base.apkg
Package has been generated: Peace Offering.apkg
Package has been generated: Measuring Things.apkg
Package has been generated: Navigation Class.apkg
Package has been generated: Talking about the Crew.apkg
Package has been generated: Fuel Your Vocab: Human Interests.apkg
Package has been generated: Love and Hate.apkg
Package has been generated: Mayday!.apkg
Package has been generated: Phrases: Sound like a Native.apkg
Package has been generated: Exploration.apkg
Package has been generated: Fuel Your Vocab: Times.apkg
Package has been generated: We're Going To ....apkg
Package has been generated: Fuel Your Vocab: Numbers.apkg
Package has been generated: Months and Dates.apkg
Package has been generated: Bargaining.apkg
Package has been generated: Fuel Your Vocab: Furniture.apkg
Package has been generated: Fuel Your Vocab: Furniture.apkg
Package has been generated: Exploration.apkg
Package has been generated: Setting a Course.apkg
Package has been generated: Phrases: Impress Them!.apkg
Package has been generated: Numbers.apkg
Package has been generated: Keeping Busy.apkg
Package has been generated: Next Summer on Earth ....apkg
Package has been generated: Staying on Board.apkg
Package has been generated: Exploration.apkg
Package has been generated: Days and Birthdays.apkg
_Error: ENOENT: no such file or directory, open 'C:\Users\Hero\How long?.apkg'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.writeFileSync (fs.js:1300:33)
    at ankiDeck.save.then.zip (C:\Users\Hero\AppData\Roaming\npm\node_modules\me
manki-cli\node_modules\memanki\index.js:8:8)_
    at <anonymous>

**Comment by matthieu-rolland** [comment]
I wonder if it could be because of the question mark in the file name... if that's the case I definitely need to deal with it. You are using windows, right?

I will have a look at it, thanks for feed back !

**Comment by matthieu-rolland** [comment]
I can't replicate this behavior on my machine, it works fine. But I'm on mac os and you seem to be on windows, that could be why. I'll try to find a windows machine where I can try this.
