### ISSUE TITLE
memanki exits after DeprecationWarning without generating a deck

### ISSUE THREAD

**Issue by harabat** [breizoreol/memanki-cli#2]
Hi,

memanki throws a `DeprecationWarning` and exits without generating a deck. I haven't touched JS in a long while, but can have a look if you pinpoint the issue. 

With merge:

```
memanki --merge --id 66669
```

Output:
```
(node:95520) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:95520) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 13.248.133.97:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
(node:95520) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:95520) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.                                                                                                                                                                                  /3m-8.5s
```

Without merge:
```
memanki --id 66669
```
Output:
```
(node:95932) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:95932) UnhandledPromiseRejectionWarning: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.socketOnEnd (_http_client.js:493:23)
    at TLSSocket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1226:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:95932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:95932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Cheers!

**Comment by harabat** [comment]
Looking at the Memrise URLs and a [comment](https://ankiweb.net/shared/info/2071525018) about an Anki add-on with a similar purpose, I tried replacing instances of `www.memrise.com` with `app.memrise.com` (found in `memparse` only, not in `memanki` or `memanki-cli`), but this didn't solve the issue.

**Comment by ctretyak** [comment]
any updates?
